Zad/Models/Dane.cs
using System.ComponentModel.DataAnnotations;

namespace Zad.Models
{
    public class Dane
    {

        [Required(ErrorMessage = "Prosze podaj Imie")]
        [MinLength(2)]
        public string Imie { get; set; }

        [Required(ErrorMessage = "Prosze podaj Nazwisko")]
        [MinLength(2)]
        public string Nazwisko { get; set; }

        [Required(ErrorMessage = "Prosze podaj Email")]
        //[RegularExpression(".+\\@.+\\.[a-z]{2,3}")]
        [EmailAddress]
        public string Email { get; set; }

        [Required(ErrorMessage = "Prosze podaj hasło skladające się z min. 8 znaków, w tym jedna wielka litera, jedna mała i jedna cyfra")]
        [DataType(DataType.Password)]
        [RegularExpression("^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)[a-zA-Z\\d]{8,}$")]
        public string Haslo { get; set; }

        [Required(ErrorMessage = "Prosze powtórz hasło; musi być takie samo")]
        [Compare ("Haslo")]
        public string PowtorzHaslo { get; set; }

        [Phone(ErrorMessage ="Podaj poprawny numer telefonu 9cyfr")]
        public string Tel { get; set; }

        [Range(11, 80, ErrorMessage="Wiek musi być większy niż 10 lat i mniejszy niż 80 lat")]
        public int Wiek { get; set; }
        [EnumDataType(typeof(Kategorie) ,ErrorMessage ="Wybierz poprawną kategorię z podanych")]
        public string Miasto { get; set; }
       
        public enum Kategorie
        {
            Szczecin,
            Warszawa,
            Poznan,
            Krakow,
            Wroclaw

        }
        //public string Temat { get; set; }
        //[Required(ErrorMessage = "Prosze podaj Temat")]
        //public string Tresc { get; set; }

        //[Required(ErrorMessage = "Prosze podaj Tresc wiadomosci")]
        //[MinLength(10), MaxLength(50)]
    }
}

Zad/Models/ErrorViewModel.cs
namespace Zad.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Zad/Controllers/DaneController.cs
using Microsoft.AspNetCore.Mvc;
using Zad.Models;

namespace Zad.Controllers
{
    public class DaneController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Form()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Form(Dane dane)
        {
            if (ModelState.IsValid)
            {
                return View("Wynik", dane);
            }else return View();
           
        }
        public IActionResult Wynik(Dane dane)
        {

            return View(dane);
        }

    }
}

Zad/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Zad.Models;

namespace Zad.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Zad/Views/Dane/Form.cshtml
@model Zad.Models.Dane
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@* 
<form asp-action="Form" method="post">
    <div>
        <label asp-for="Imie">Twoje imie</label>
        <input asp-for="Imie" />
    </div>
    <div>
        <label asp-for="Email">TTwoj email</label>
        <input asp-for="Email" />
    </div>
    <div>
        <label asp-for="Temat">Temat</label>
        <input asp-for="Temat" />
    </div>
    <div>
        <label asp-for="Tresc">Tresc</label>
        <input asp-for="Tresc" />
    </div>
    <div><input type="submit" /></div>
</form> *@
@using (Html.BeginForm("Form", "Dane", FormMethod.Post, new { id = "FormId" }))
{ 
    @Html.ValidationSummary(false, "", new {@class="text-danger"})
    <p>Twoje imie: @Html.TextBoxFor(a=>a.Imie)</p>
    <p>Nazwisko: @Html.TextBoxFor(a=>a.Nazwisko)</p>
    <p>Twój email: @Html.TextBoxFor(a=>a.Email)</p>
   // <p>Temat: @Html.TextBoxFor(a=>a.Temat)</p>
    //<p>Tresc: @Html.TextBoxFor(a=>a.Tresc)</p>
    <p>Podaj hasło: @Html.TextBoxFor(a=>a.Haslo)</p>
    <p>Powtórz hasło: @Html.TextBoxFor(a=>a.PowtorzHaslo)</p>
    <p>Numer telefonu: @Html.TextBoxFor(a=>a.Tel)</p>
    <p>Wiek: @Html.TextBoxFor(a=>a.Wiek)</p>
    <p>Miasto: 
    <select asp-for="Miasto"
            asp-items="Html.GetEnumSelectList<Dane.Kategorie>()">
        </select>
    </p>
    <input type="submit" value="Prześlij" />
    <input type="button" value="Wyczyść" onclick="ResetForm();" />
    
   

}

<script>
    function ResetForm() {
        document.getElementById('FormId').reset();
    }
</script>

Zad/Views/Dane/Wynik.cshtml
@model Zad.Models.Dane
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{



}

<h1>Wynik</h1>

   Potwierdzam Twoje dane
       Imie: @Model.Imie
<br />
   Email: @Model.Email
<br />
@* Temat: @Model.Temat
<br />
Tresc: @Model.Tresc
<br /> *@
<h1>Rejestracja zakończona pomyślnie</h1>

Zad/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Zad/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Zad</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Zad.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Zad</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Dane" asp-action="Form">Form</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Zad - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>